# Generated by Django 5.1.3 on 2025-05-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField(null=True)),
                ('chars', models.CharField(max_length=255)),
                ('chars_choices', models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four')], max_length=255)),
                ('integer', models.IntegerField()),
                ('integer_choices', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('float', models.FloatField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', models.CharField(max_length=255)),
                ('integer', models.IntegerField()),
                ('float', models.FloatField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('model_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.modela')),
            ],
        ),
        migrations.AddField(
            model_name='modela',
            name='model_b',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='example.modelb'),
        ),
    ]
