# Generated by Django 5.1.3 on 2025-05-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modela',
            name='boolean',
            field=models.BooleanField(null=True),
        ),
    ]
