# Generated by Django 5.2.4 on 2025-09-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchkit', '0002_rename_searchkitsearch_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
